### ISSUE TITLE
Simplify Stream Tester architecture

### ISSUE THREAD

**Issue by leszko** [livepeer/stream-tester#145]
Stream tester use case is quite simple:
- Send test data to each active O
- Record the metrics around it
- Store the metrics in Leaderboard

However, currently the architecture is complete. You need 4 services:
- Stream Tester
- Orch Tester
- Broadcaster
- Monitoring

This does not only require a lot of resources, but it's also very hard to reason about the issues with stream tester. Moreover, it's hard to run stream-tester locally.

We should check if it's possible to simplify the Stream Tester architecture, maybe even make it a self-container process which can be run locally.

**Comment by victorges** [comment]
I wonder if we need a separate/proper `orch-tester` command to do specifically this orchestrator testing.

I know that, for example, `record-tester` (in this same repo) does go through the whole stack, but it's because it is actually our E2E tester. I believe `stream-tester` is also used like that in some contexts, like for example to test if a region is currently healthy when we get some alarms on #incident-response.

So I guess either we would make this new behavior an option on the `stream-tester` execution, to make it go directly to orchestrators, or maybe it should be this whole new `orch-tester` cmd instead, which will probably make its code much more focused/simpler as well. WDYT?

**Comment by leszko** [comment]
I need to do some design/research, but now I believe we should end up with a separate command with possible very little (or even zero) dependencies on other services.
