### ISSUE TITLE
Update alpine base Docker image

### ISSUE THREAD

**Issue by leszko** [livepeer/stream-tester#154]
Our Dockerfile does not work with the latest alpine image (`3.16.0`). It builds correctly, but running streamtester results in the following error:

```
Error loading shared library libavformat.so.58: No such file or directory (needed by /root/streamtester)
Error loading shared library libavutil.so.56: No such file or directory (needed by /root/streamtester)
Error loading shared library libavcodec.so.58: No such file or directory (needed by /root/streamtester)
Error relocating /root/streamtester: avcodec_find_decoder: symbol not found
Error relocating /root/streamtester: avcodec_decode_video2: symbol not found
Error relocating /root/streamtester: av_register_all: symbol not found
Error relocating /root/streamtester: av_frame_alloc: symbol not found
Error relocating /root/streamtester: av_init_packet: symbol not found
Error relocating /root/streamtester: av_free_packet: symbol not found
Error relocating /root/streamtester: avcodec_open2: symbol not found
Error relocating /root/streamtester: avcodec_encode_video2: symbol not found
Error relocating /root/streamtester: avcodec_find_encoder: symbol not found
Error relocating /root/streamtester: avcodec_alloc_context3: symbol not found
Error relocating /root/streamtester: av_log_set_level: symbol not found
```

For now, I've hardcoded the alpine version to `3.15.4` in https://github.com/livepeer/stream-tester/pull/153

**Comment by iameli** [comment]
Interesting - it's my experience that `No such file or directory` in this context usually means it can't find a shared library that it's expecting rather than the library itself missing. Would run `ldd <binary>` and see if anything's missing

**Comment by cyberj0g** [comment]
The root cause is that `golang:1.15-alpine` build image uses apk package [ffmpeg-4.4.1r2](https://pkgs.alpinelinux.org/package/v3.15/community/x86/ffmpeg), while run image, if created from latest alpine, uses [ffmpeg-5.0.1r1](https://pkgs.alpinelinux.org/package/edge/community/armhf/ffmpeg). These packages have `libavcodec.so` et al of versions 58 and 59 correspondingly. I think, it's best to have docker image versions pinned to avoid this happening again, so @leszko 's update already fixes the issue.
